name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "d8bd3e473bfd4eb1a7f5f5b7dacd54ba" },
  { binding = "SHARE", id = "90a5bbdf6149463d9e7b503c4cac3f76" }
]